### ISSUE TITLE
Allow order modification in KITE & UPSTOX

### ISSUE THREAD

**Issue by Pritesh-Mhatre** [Pritesh-Mhatre/autotrader#2]
Allow modification of normal, bo & co. Modification of target & s/l in BO; once it is executed.
The BO modify function should look somewhat like:
modifyTarget(parentId, newTarget);

Request from: comp.vijay@gmail.com, pandianr2005@gmail.com

**Comment by Pritesh-Mhatre** [comment]
This feature requires considerable amount of development efforts, we will start on it soon.

**Comment by VijayKumarSingh2006** [comment]
Hi Pritesh,

Have you started on this, I am waiting for this function. Please give some priority to it soon.

**Comment by Pritesh-Mhatre** [comment]
Tentative delivery dates: 11th or 18th of January

**Comment by VijayKumarSingh2006** [comment]
Thanks for update.

**Comment by Pritesh-Mhatre** [comment]
Changes are successfully tested for KITE. Following new functions added:

modifyOrder(orderId, orderType, quantity, price, triggerPrice)
modifyOrderPrice(orderId, price)
modifyOrderQuantity(orderId, quantity)

Next is adding modification support for Upstox, work in progress...

**Comment by VijayKumarSingh2006** [comment]
Thanks a lot Pritesh for giving it before promised date.

Thanks & Regards,
Vijay Kumar Singh

**Comment by Pritesh-Mhatre** [comment]
It's ready but will only go live on 11th, as I am not available for support this weekend.

**Comment by VijayKumarSingh2006** [comment]
No problem. Will wait till then.

Thanks & Regards,
Vijay Kumar Singh

On 03-Jan-2019 2:41 PM, "Pritesh Mhatre" <notifications@github.com> wrote:

It's ready but will only go live on 11th, as I am not available for support
this weekend.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Pritesh-Mhatre/autotrader/issues/2#issuecomment-451087941>,
or mute the thread

**Comment by Pritesh-Mhatre** [comment]
Successfully tested on Upstox, closing the enhancement.
